package com.hms.service;

import com.hms.entity.Appointment;
import com.hms.entity.Patient;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.ByteArrayOutputStream;
import org.springframework.stereotype.Service;

@Service
public class PdfService {

    public byte[] generateAppointmentSlip(Appointment appointment) {
        try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
            Document document = new Document();
            PdfWriter.getInstance(document, outputStream);
            document.open();

            Font heading = new Font(Font.FontFamily.HELVETICA, 16, Font.BOLD);
            Paragraph title = new Paragraph("Appointment Slip", heading);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);
            document.add(new Paragraph(" "));

            PdfPTable table = new PdfPTable(2);
            table.setWidthPercentage(100);
            addRow(table, "Appointment ID", String.valueOf(appointment.getId()));
            addRow(table, "Patient", appointment.getPatient().getName());
            addRow(table, "Doctor", appointment.getDoctor().getName());
            addRow(table, "Date", String.valueOf(appointment.getAppointmentDate()));
            addRow(table, "Time Slot", appointment.getTimeSlot());
            addRow(table, "Status", String.valueOf(appointment.getStatus()));
            addRow(table, "Fee", String.valueOf(appointment.getDoctor().getConsultationFee()));
            document.add(table);

            document.add(new Paragraph(" "));
            document.add(new Paragraph("Generated by Hospital Management System"));
            document.close();
            return outputStream.toByteArray();
        } catch (Exception ex) {
            throw new IllegalStateException("Unable to generate appointment slip", ex);
        }
    }

    public byte[] generatePatientReport(Patient patient) {
        try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
            Document document = new Document();
            PdfWriter.getInstance(document, outputStream);
            document.open();

            Font heading = new Font(Font.FontFamily.HELVETICA, 16, Font.BOLD);
            Paragraph title = new Paragraph("Patient Medical Report", heading);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);
            document.add(new Paragraph(" "));

            PdfPTable table = new PdfPTable(2);
            table.setWidthPercentage(100);
            addRow(table, "Patient ID", String.valueOf(patient.getId()));
            addRow(table, "Name", patient.getName());
            addRow(table, "Age", String.valueOf(patient.getAge()));
            addRow(table, "Gender", String.valueOf(patient.getGender()));
            addRow(table, "Contact", patient.getContactNumber());
            addRow(table, "Registered On", String.valueOf(patient.getRegistrationDate()));
            addRow(table, "Medical History", patient.getMedicalHistory() == null ? "N/A" : patient.getMedicalHistory());
            document.add(table);

            document.close();
            return outputStream.toByteArray();
        } catch (Exception ex) {
            throw new IllegalStateException("Unable to generate patient report", ex);
        }
    }

    private void addRow(PdfPTable table, String key, String value) {
        PdfPCell keyCell = new PdfPCell(new Paragraph(key));
        PdfPCell valueCell = new PdfPCell(new Paragraph(value));
        keyCell.setPadding(6f);
        valueCell.setPadding(6f);
        table.addCell(keyCell);
        table.addCell(valueCell);
    }
}
